name: Go

on:
  push:
    branches: [ master ]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://fluxy/gotessa:latest
        id: gotessa
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.QA_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.QA_WEBHOOK_SECRET }}
          data: ${{ steps.gotessa.outputs.gotessa_json }}
